/**
 * @vitest-environment happy-dom
 *
 * ArrowTool produces a `<g data-type="arrow">` carrying endpoint
 * data attrs + per-end arrow specs, with stem + head children
 * generated by `refreshArrowPath`. The tool reaches into the
 * CanvasManager surface directly (`canvas.annotations`,
 * `history.save()`) rather than going through ToolDOMSurface, so
 * tests use the canvas-form constructor with a minimal
 * CanvasManager / History stub.
 *
 * Coverage focus:
 *   - pointerdown creates the group with shared stroke attrs +
 *     initial endpoints + the per-end specs from options.
 *   - pointermove rewrites endpoints and refreshes the path.
 *   - pointerup commits via history.save when the drag is long
 *     enough; aborts when the drag is too short (<5px).
 *   - applyArrowHead / detectArrowEnds round-trip a per-end
 *     descriptor cleanly.
 *   - canonicalShape rejects unknown shapes (defaults to "none").
 */

import type { ToolOptions } from "@ingcreators/annot-core/editor/tool-options";
import { describe, expect, it, vi } from "vitest";
import type { CanvasManager } from "../canvas-manager.js";
import type { History } from "../history.js";
import { ArrowTool, applyArrowHead, detectArrowEnds } from "./arrow-tool.js";

const SVG_NS = "http://www.w3.org/2000/svg";

function makeCanvas(): { canvas: CanvasManager; annotations: SVGGElement } {
  const annotations = document.createElementNS(SVG_NS, "g") as SVGGElement;
  const canvas = { annotations } as unknown as CanvasManager;
  return { canvas, annotations };
}

function makeHistory(): { history: History; save: ReturnType<typeof vi.fn> } {
  const save = vi.fn();
  return { history: { save } as unknown as History, save };
}

function makeOptions(overrides: Partial<ToolOptions> = {}): ToolOptions {
  return {
    strokeColor: "#000000",
    fillColor: "#ffffff",
    strokeWidth: 3,
    fontSize: 14,
    strokeDasharray: "",
    fillOpacity: 1,
    ...overrides,
  };
}

function makePoint(x: number, y: number): DOMPoint {
  return new DOMPoint(x, y);
}

function pointerEvent(): PointerEvent {
  const Ctor =
    typeof PointerEvent === "function" ? PointerEvent : (MouseEvent as typeof PointerEvent);
  return new Ctor("pointerdown", { bubbles: true });
}

describe("ArrowTool — pointerdown setup", () => {
  it('attaches a <g data-type="arrow"> with shared stroke attributes from options', () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(
      canvas,
      history,
      makeOptions({ strokeColor: "#ff0000", strokeWidth: 5 }),
    );
    tool.onPointerDown(pointerEvent(), makePoint(10, 20));
    expect(annotations.children.length).toBe(1);
    const g = annotations.firstElementChild!;
    expect(g.tagName.toLowerCase()).toBe("g");
    expect(g.getAttribute("data-type")).toBe("arrow");
    expect(g.getAttribute("stroke")).toBe("#ff0000");
    expect(g.getAttribute("stroke-width")).toBe("5");
  });

  it("seeds endpoints at (startX, startY) → (startX, startY) (zero-length until pointermove)", () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions());
    tool.onPointerDown(pointerEvent(), makePoint(10, 20));
    const g = annotations.firstElementChild!;
    expect(g.getAttribute("data-x1")).toBe("10");
    expect(g.getAttribute("data-y1")).toBe("20");
    expect(g.getAttribute("data-x2")).toBe("10");
    expect(g.getAttribute("data-y2")).toBe("20");
  });

  it("writes per-end arrow specs from options.arrow* (start defaults to 'none', end to 'triangle')", () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions());
    tool.onPointerDown(pointerEvent(), makePoint(0, 0));
    const g = annotations.firstElementChild!;
    expect(g.getAttribute("data-arrow-start-shape")).toBe("none");
    expect(g.getAttribute("data-arrow-end-shape")).toBe("triangle");
    expect(g.getAttribute("data-arrow-start-width")).toBe("md");
    expect(g.getAttribute("data-arrow-end-width")).toBe("md");
  });

  it("respects explicit per-end overrides from options", () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(
      canvas,
      history,
      makeOptions({
        arrowHeadStart: "diamond",
        arrowHeadEnd: "stealth",
        arrowWidthStart: "sm",
        arrowLengthEnd: "lg",
      }),
    );
    tool.onPointerDown(pointerEvent(), makePoint(0, 0));
    const g = annotations.firstElementChild!;
    expect(g.getAttribute("data-arrow-start-shape")).toBe("diamond");
    expect(g.getAttribute("data-arrow-end-shape")).toBe("stealth");
    expect(g.getAttribute("data-arrow-start-width")).toBe("sm");
    expect(g.getAttribute("data-arrow-end-length")).toBe("lg");
  });

  it("emits an opacity attribute when strokeOpacity < 1", () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions({ strokeOpacity: 0.4 }));
    tool.onPointerDown(pointerEvent(), makePoint(0, 0));
    expect(annotations.firstElementChild!.getAttribute("opacity")).toBe("0.4");
  });

  it("does NOT emit an opacity attribute when strokeOpacity is unset or 1", () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions({ strokeOpacity: 1 }));
    tool.onPointerDown(pointerEvent(), makePoint(0, 0));
    expect(annotations.firstElementChild!.hasAttribute("opacity")).toBe(false);
  });

  it("emits stroke-linecap when set in options", () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions({ strokeLinecap: "round" }));
    tool.onPointerDown(pointerEvent(), makePoint(0, 0));
    expect(annotations.firstElementChild!.getAttribute("stroke-linecap")).toBe("round");
  });
});

describe("ArrowTool — pointermove updates endpoints", () => {
  it("rewrites data-x2 / data-y2 to track the cursor", () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions());
    tool.onPointerDown(pointerEvent(), makePoint(0, 0));
    tool.onPointerMove(pointerEvent(), makePoint(100, 50));
    const g = annotations.firstElementChild!;
    expect(g.getAttribute("data-x1")).toBe("0");
    expect(g.getAttribute("data-y1")).toBe("0");
    expect(g.getAttribute("data-x2")).toBe("100");
    expect(g.getAttribute("data-y2")).toBe("50");
  });

  it("multiple moves leave the latest endpoint in place", () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions());
    tool.onPointerDown(pointerEvent(), makePoint(0, 0));
    tool.onPointerMove(pointerEvent(), makePoint(50, 50));
    tool.onPointerMove(pointerEvent(), makePoint(100, 75));
    const g = annotations.firstElementChild!;
    expect(g.getAttribute("data-x2")).toBe("100");
    expect(g.getAttribute("data-y2")).toBe("75");
  });

  it("pointermove without a prior pointerdown is a silent no-op", () => {
    const { canvas, annotations } = makeCanvas();
    const { history } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions());
    expect(() => tool.onPointerMove(pointerEvent(), makePoint(50, 50))).not.toThrow();
    expect(annotations.children.length).toBe(0);
  });
});

describe("ArrowTool — pointerup commit / abort", () => {
  it("saves history + fires onShapeComplete on a long-enough drag", () => {
    const { canvas, annotations } = makeCanvas();
    const { history, save } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions());
    const onShapeComplete = vi.fn();
    tool.onShapeComplete = onShapeComplete;
    tool.onPointerDown(pointerEvent(), makePoint(0, 0));
    tool.onPointerMove(pointerEvent(), makePoint(100, 0));
    tool.onPointerUp(pointerEvent(), makePoint(100, 0));
    expect(save).toHaveBeenCalledTimes(1);
    expect(onShapeComplete).toHaveBeenCalledTimes(1);
    expect(annotations.children.length).toBe(1);
  });

  it("removes the group + does NOT save history when the drag is too short (<5px)", () => {
    const { canvas, annotations } = makeCanvas();
    const { history, save } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions());
    const onShapeComplete = vi.fn();
    tool.onShapeComplete = onShapeComplete;
    tool.onPointerDown(pointerEvent(), makePoint(0, 0));
    // 3px of movement → sqrt(2*2 + 2*2) ≈ 2.83 < 5 threshold
    tool.onPointerMove(pointerEvent(), makePoint(2, 2));
    tool.onPointerUp(pointerEvent(), makePoint(2, 2));
    expect(annotations.children.length).toBe(0);
    expect(save).not.toHaveBeenCalled();
    expect(onShapeComplete).not.toHaveBeenCalled();
  });

  it("pointerup without a prior pointerdown is a silent no-op", () => {
    const { canvas, annotations } = makeCanvas();
    const { history, save } = makeHistory();
    const tool = new ArrowTool(canvas, history, makeOptions());
    expect(() => tool.onPointerUp(pointerEvent(), makePoint(10, 10))).not.toThrow();
    expect(annotations.children.length).toBe(0);
    expect(save).not.toHaveBeenCalled();
  });
});

describe("applyArrowHead + detectArrowEnds round-trip", () => {
  function makeArrow(): SVGGElement {
    const g = document.createElementNS(SVG_NS, "g") as SVGGElement;
    g.setAttribute("data-type", "arrow");
    g.setAttribute("data-x1", "0");
    g.setAttribute("data-y1", "0");
    g.setAttribute("data-x2", "100");
    g.setAttribute("data-y2", "0");
    return g;
  }

  it("writes the per-end specs and a regenerated path is reachable on the element", () => {
    const arrow = makeArrow();
    applyArrowHead(arrow, {
      start: { shape: "oval", width: "lg", length: "sm" },
      end: { shape: "diamond", width: "md", length: "md" },
    });
    expect(arrow.getAttribute("data-arrow-start-shape")).toBe("oval");
    expect(arrow.getAttribute("data-arrow-start-width")).toBe("lg");
    expect(arrow.getAttribute("data-arrow-start-length")).toBe("sm");
    expect(arrow.getAttribute("data-arrow-end-shape")).toBe("diamond");
    // Stem path child created on the fly by refreshArrowPath.
    expect(arrow.querySelector('[data-role="stem"]')).not.toBeNull();
  });

  it("detectArrowEnds reads the matching descriptor back", () => {
    const arrow = makeArrow();
    applyArrowHead(arrow, {
      start: { shape: "stealth", width: "sm", length: "sm" },
      end: { shape: "triangle", width: "lg", length: "lg" },
    });
    expect(detectArrowEnds(arrow)).toEqual({
      start: { shape: "stealth", width: "sm", length: "sm" },
      end: { shape: "triangle", width: "lg", length: "lg" },
    });
  });

  it("detectArrowEnds normalises an unknown shape attribute to 'none'", () => {
    const arrow = makeArrow();
    arrow.setAttribute("data-arrow-start-shape", "garbage-value");
    arrow.setAttribute("data-arrow-end-shape", "");
    const ends = detectArrowEnds(arrow);
    expect(ends.start.shape).toBe("none");
    expect(ends.end.shape).toBe("none");
  });

  it("detectArrowEnds defaults width/length to 'md' when neither side specified them", () => {
    const arrow = makeArrow();
    arrow.setAttribute("data-arrow-start-shape", "triangle");
    expect(detectArrowEnds(arrow).start).toEqual({
      shape: "triangle",
      width: "md",
      length: "md",
    });
  });
});
