import { computeDasharray } from "@ingcreators/annot-core/utils";
import {
  type ArrowSpec,
  detectArrowSpec,
  refreshArrowPath,
  writeArrowEndpoints,
  writeArrowSpec,
} from "@ingcreators/annot-core/editor/arrow-markers";
import type { ArrowHead, ArrowShape } from "./tool-base.js";
/**
 * ArrowTool — unified Line / Arrow tool.
 *
 * Produces a single `<path data-type="arrow">` element carrying:
 *   - `data-x1 / data-y1 / data-x2 / data-y2`  geometric endpoints
 *   - `data-arrow-start-shape / -width / -length`  per-end arrow spec
 *   - `data-arrow-end-shape   / -width / -length`  per-end arrow spec
 *   - `d` = composed stem + arrow-head subpaths (generated by
 *           `computeArrowPath` in arrow-markers.ts)
 *
 * The `<path>` replaces the prior `<line>` + SVG `<marker>` combo.
 * Composing the stem and arrow head into one path lets us shorten
 * the stem at each end (via the maxGraph-derived trig offsets) so
 * the stroke cap never pokes past the head, and lets filled heads
 * (triangle / diamond / oval) and open heads (chevron) coexist on
 * opposite ends of the same line — filled subpaths are closed
 * (`Z`), open ones aren't, and the shared `fill=stroke` paint only
 * affects the closed ones.
 */
import { ToolBase } from "./tool-base.js";

export interface ArrowEndsSpec {
  start: ArrowSpec;
  end: ArrowSpec;
}

/** Remap legacy / pre-refactor shape names to the PowerPoint-parity
 *  six-shape set. */
function canonicalShape(value: string | null): ArrowShape {
  switch (value) {
    case "arrow":
    case "triangle":
    case "stealth":
    case "diamond":
    case "oval":
    case "none":
      return value;
    case "triangle-open":
      return "arrow";
    case "tbar":
      return "stealth";
    case "reverse":
      return "arrow";
    default:
      return "triangle";
  }
}

/** Translate the legacy 3-state `ArrowHead` value into a full
 *  per-end ArrowEndsSpec (default md/md dimensions). */
export function fromLegacyArrowHead(head: ArrowHead | undefined): ArrowEndsSpec {
  const none: ArrowSpec = { shape: "none", width: "md", length: "md" };
  const tri: ArrowSpec = { shape: "triangle", width: "md", length: "md" };
  switch (head) {
    case "none":
      return { start: none, end: none };
    case "both":
      return { start: tri, end: tri };
    default:
      return { start: none, end: tri };
  }
}

/**
 * Apply a per-end arrow spec to an arrow `<path>` element:
 *   - writes data-arrow-*-{shape,width,length} attributes
 *   - regenerates the path's `d` (stem + heads)
 *   - updates `fill` (= stroke color if any filled head, else "none")
 *
 * Accepts either an `ArrowHead` (legacy 3-state) or an
 * `ArrowEndsSpec` (new per-end / per-dim).
 */
export function applyArrowHead(el: SVGElement, head: ArrowHead): void;
export function applyArrowHead(el: SVGElement, spec: ArrowEndsSpec): void;
export function applyArrowHead(el: SVGElement, v: ArrowHead | ArrowEndsSpec): void {
  const spec: ArrowEndsSpec = typeof v === "string" ? fromLegacyArrowHead(v) : v;
  writeArrowSpec(el, "start", spec.start);
  writeArrowSpec(el, "end", spec.end);

  // Legacy single-field discriminator for code paths that haven't
  // migrated (Office paste fallback, `detectArrowHead`).
  const hasStart = spec.start.shape !== "none";
  const hasEnd = spec.end.shape !== "none";
  const legacy: ArrowHead = hasStart && hasEnd ? "both" : hasStart || hasEnd ? "end" : "none";
  el.setAttribute("data-arrow-head", legacy);

  refreshArrowPath(el);
}

/** Read the full per-end descriptor off an arrow element, falling
 *  back through layered legacy attributes for pre-refactor content. */
export function detectArrowEnds(el: SVGElement): ArrowEndsSpec {
  // Prefer the canonical data attrs from arrow-markers' detectArrowSpec.
  const startRaw = el.getAttribute("data-arrow-start-shape");
  const endRaw = el.getAttribute("data-arrow-end-shape");
  if (startRaw || endRaw) {
    return {
      start: {
        shape: canonicalShape(startRaw),
        width: detectArrowSpec(el, "start").width,
        length: detectArrowSpec(el, "start").length,
      },
      end: {
        shape: canonicalShape(endRaw),
        width: detectArrowSpec(el, "end").width,
        length: detectArrowSpec(el, "end").length,
      },
    };
  }
  // Legacy: element has the 3-state `data-arrow-head` or plain marker
  // attributes.
  const legacy =
    (el.getAttribute("data-arrow-head") as ArrowHead | null) ||
    (el.hasAttribute("marker-start") && el.hasAttribute("marker-end")
      ? "both"
      : el.hasAttribute("marker-end") || el.hasAttribute("marker-start")
        ? "end"
        : "none");
  return fromLegacyArrowHead(legacy);
}

/** Legacy 3-state detector — still used by Office-paste paths that
 *  haven't migrated to reading the per-end spec. */
export function detectArrowHead(el: SVGElement): ArrowHead {
  const spec = detectArrowEnds(el);
  const hasStart = spec.start.shape !== "none";
  const hasEnd = spec.end.shape !== "none";
  return hasStart && hasEnd ? "both" : hasEnd || hasStart ? "end" : "none";
}

export class ArrowTool extends ToolBase {
  readonly name = "arrow";
  /** The outer `<g data-type="arrow">` wrapping stem + heads. */
  #group: SVGGElement | null = null;
  #drawing = false;
  #startX = 0;
  #startY = 0;

  onPointerDown(_e: PointerEvent, pt: DOMPoint): void {
    this.#drawing = true;
    this.#startX = pt.x;
    this.#startY = pt.y;

    // Compose the initial spec from the per-dim fields. The
    // `arrowHead` 3-state field is the second source — accepted as a
    // fallback when the per-end `arrowHead{Start,End}` are unset.
    const spec: ArrowEndsSpec = {
      start: {
        shape: this.options.arrowHeadStart ?? "none",
        width: this.options.arrowWidthStart ?? "md",
        length: this.options.arrowLengthStart ?? "md",
      },
      end: {
        shape: this.options.arrowHeadEnd ?? "triangle",
        width: this.options.arrowWidthEnd ?? "md",
        length: this.options.arrowLengthEnd ?? "md",
      },
    };
    if (
      this.options.arrowHeadStart == null &&
      this.options.arrowHeadEnd == null &&
      this.options.arrowHead
    ) {
      const legacy = fromLegacyArrowHead(this.options.arrowHead);
      spec.start = legacy.start;
      spec.end = legacy.end;
    }

    const sw = this.options.strokeWidth;
    // Shared stroke attributes live on the <g> so they cascade to
    // both the stem <path> and the head <path>. The head overrides
    // `stroke-dasharray` to "none" inside refreshArrowPath so a
    // dashed stem doesn't produce a dashed arrow outline.
    const g = this.createSVG("g", {
      "data-type": "arrow",
      stroke: this.options.strokeColor,
      "stroke-width": String(sw),
      "stroke-dasharray": computeDasharray(this.options.strokeDasharray, sw),
      "data-dash-key": this.options.strokeDasharray,
    });
    if (this.options.strokeOpacity != null && this.options.strokeOpacity < 1) {
      g.setAttribute("opacity", String(this.options.strokeOpacity));
    }
    if (this.options.strokeLinecap) {
      g.setAttribute("stroke-linecap", this.options.strokeLinecap);
    }

    writeArrowEndpoints(g, pt.x, pt.y, pt.x, pt.y);
    writeArrowSpec(g, "start", spec.start);
    writeArrowSpec(g, "end", spec.end);
    // Legacy 3-state discriminator (Office-paste back-compat).
    const hasStart = spec.start.shape !== "none";
    const hasEnd = spec.end.shape !== "none";
    g.setAttribute(
      "data-arrow-head",
      hasStart && hasEnd ? "both" : hasStart || hasEnd ? "end" : "none",
    );

    // refreshArrowPath creates the stem + head <path> children on
    // demand and populates their `d` + fill. Calling it here sets up
    // the initial geometry even though x1=x2=y1=y2 (zero-length line
    // — visually nothing yet).
    refreshArrowPath(g);
    this.#group = g;

    this.canvas.annotations.appendChild(g);
  }

  onPointerMove(_e: PointerEvent, pt: DOMPoint): void {
    if (!this.#drawing || !this.#group) return;
    writeArrowEndpoints(this.#group, this.#startX, this.#startY, pt.x, pt.y);
    refreshArrowPath(this.#group);
  }

  onPointerUp(_e: PointerEvent, pt: DOMPoint): void {
    if (!this.#drawing || !this.#group) return;
    this.#drawing = false;
    const dx = pt.x - this.#startX;
    const dy = pt.y - this.#startY;
    if (Math.sqrt(dx * dx + dy * dy) < 5) {
      this.#group.remove();
    } else {
      this.history.save();
      this.onShapeComplete?.(this.#group);
    }
    this.#group = null;
  }
}
