// @ts-check

import sitemap from "@astrojs/sitemap";
import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";

// Astro config for annot.work/docs — Starlight-powered docs site.
//
// Phase 1 of `docs/plans/annot-work-astro-unification.md`. Built in
// parallel with the legacy VitePress site at `packages/docs-site/`
// during the migration; takes over the production /docs/* route
// in Phase 6 (feature-flag cutover) and is renamed to `docs-site`
// in Phase 7.
//
// `base: "/docs/"` matches the VitePress predecessor so internal
// links keep the same on-disk paths. `outDir: "./dist/docs"` nests
// the build output one level deeper so the Cloudflare Workers
// static-asset binding maps `annot.work/docs/foo` →
// `<assets.directory>/docs/foo/index.html`. Same dance the
// VitePress build does, same reason.
//
// `trailingSlash: "ignore"` matches the existing marketing site
// (`packages/marketing/astro.config.mjs`) and preserves both
// `/docs/getting-started` and `/docs/getting-started/` resolving
// to the same page — matching VitePress's pre-migration behaviour
// so external links don't break.
//
// `site` is the canonical production origin — emitted into
// sitemap.xml and OG metadata. Marketing already uses the same
// origin; the unified value is intentional.
export default defineConfig({
  site: "https://annot.work",
  base: "/docs/",
  trailingSlash: "ignore",
  outDir: "./dist/docs",
  build: {
    format: "directory",
  },
  integrations: [
    starlight({
      title: "Annot",
      description:
        "An SVG-first screenshot annotation toolkit. Call it from Playwright, host it in a PWA, share annotated screenshots through GitHub.",
      logo: {
        src: "./src/assets/annot-icon.svg",
        replacesTitle: false,
      },
      favicon: "/favicon.svg",
      customCss: ["./src/styles/brand.css"],
      // Starlight's built-in client-side Pagefind search covers
      // the docs surface with no Algolia / server dependency.
      // Default is enabled; explicit `pagefind: true` documents
      // the choice.
      pagefind: true,
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/ingcreators/annot",
        },
      ],
      editLink: {
        baseUrl: "https://github.com/ingcreators/annot/edit/main/packages/docs-site-astro/",
      },
      lastUpdated: true,
      // Sidebar mirrors the VitePress one in `.vitepress/config.ts`.
      // Phase 1 ships only the Home page; Phase 2 ports content
      // and the sidebar fills out organically as each section's
      // pages land.
      // Starlight 0.39+ requires `items: [{ autogenerate: ... }]`
      // for labelled autogenerated groups. Each group label lives
      // here; populating each section's `items` is Phase 2's job.
      sidebar: [
        {
          label: "Getting started",
          items: [{ autogenerate: { directory: "getting-started" } }],
        },
        {
          label: "API reference",
          items: [{ autogenerate: { directory: "api" } }],
        },
        {
          label: "Recipes",
          items: [{ autogenerate: { directory: "recipes" } }],
        },
        {
          label: "AI agents",
          items: [{ autogenerate: { directory: "ai-agents" } }],
        },
        {
          // Migration target for the legacy `/docs/pwa/*` URLs.
          // See `docs/plans/annot-work-astro-unification.md` for
          // the rename + 301 redirect rationale.
          label: "Annot web app",
          items: [{ autogenerate: { directory: "app" } }],
        },
        {
          label: "Contributing",
          items: [{ autogenerate: { directory: "contributing" } }],
        },
      ],
    }),
    sitemap(),
  ],
});
