// Phase 2 of `docs/plans/svg-icons-and-plugin-icon-spec.md`.
//
// Snapshot the registry's keys so accidental removals during
// future merges show up as a deliberate snapshot update rather
// than a silent miss. The actual SVG content is autogenerated
// from the upstream `@material-symbols/svg-400` package, so we
// snapshot the KEYS, not the values — bumping the upstream
// package and re-running the extraction script should leave
// this test green unless the host's call sites grow / shrink.

import { describe, expect, it } from "vitest";
import { BUILTIN_ICON_IDS, BUILTIN_ICONS, resolveBuiltinIcon } from "./registry.js";

describe("BUILTIN_ICONS registry", () => {
  it("exposes a stable, alphabetised id list (snapshot)", () => {
    // Keep sorted so re-runs of the extraction script + future
    // additions land deterministically.
    expect([...BUILTIN_ICON_IDS].sort()).toMatchInlineSnapshot(`
      [
        "add",
        "add_to_drive",
        "align_horizontal_center",
        "align_horizontal_left",
        "align_horizontal_right",
        "align_vertical_bottom",
        "align_vertical_center",
        "align_vertical_top",
        "apps",
        "arrow.both",
        "arrow.end",
        "arrow.none",
        "arrow_right_alt",
        "arrow_selector_tool",
        "article",
        "blur_on",
        "brand.github",
        "chat",
        "chat_bubble",
        "check_box",
        "chevron_right",
        "circle",
        "close",
        "cloud",
        "cloud_done",
        "cloud_off",
        "cloud_queue",
        "collections_bookmark",
        "content_copy",
        "content_paste",
        "counter.circle",
        "counter.rect",
        "counter.rounded",
        "counter_1",
        "create_new_folder",
        "crop",
        "crop_square",
        "dark_mode",
        "database",
        "delete",
        "desktop_windows",
        "download",
        "draw",
        "drive_file_rename_outline",
        "drive_folder_upload",
        "edit",
        "error",
        "expand_more",
        "extension",
        "file_copy",
        "flip",
        "flip_to_back",
        "flip_to_front",
        "folder",
        "folder_open",
        "grid_view",
        "group_remove",
        "group_work",
        "groups",
        "help_outline",
        "highlight",
        "history",
        "home_storage",
        "horizontal_distribute",
        "horizontal_rule",
        "hub",
        "info",
        "ink_highlighter",
        "join_inner",
        "join_left",
        "keyboard_arrow_down",
        "keyboard_arrow_up",
        "laptop",
        "library_books",
        "light_mode",
        "more_vert",
        "near_me",
        "north_east",
        "open_in_new",
        "rectangle",
        "redo",
        "refresh",
        "remove",
        "rotate_left",
        "rotate_right",
        "rounded_corner",
        "save",
        "screenshot_monitor",
        "search",
        "shape.ellipse",
        "shape.rect",
        "shape.rounded",
        "shapes",
        "share",
        "square",
        "sticky_note_2",
        "swap_horiz",
        "swap_vert",
        "sync",
        "sync_alt",
        "task",
        "text_fields",
        "timer",
        "title",
        "tune",
        "undo",
        "upload",
        "vertical_distribute",
        "view_list",
        "view_module",
        "visibility_off",
        "warning",
      ]
    `);
  });

  it("every id resolves to a non-empty <svg>…</svg> string", () => {
    for (const id of BUILTIN_ICON_IDS) {
      const svg = resolveBuiltinIcon(id);
      expect(svg, `missing or empty SVG for ${id}`).toBeTruthy();
      expect(svg!.startsWith("<svg")).toBe(true);
      expect(svg!.endsWith("</svg>")).toBe(true);
    }
  });

  it("resolveBuiltinIcon returns undefined for unknown ids (no throw)", () => {
    expect(resolveBuiltinIcon("definitely-not-a-real-id")).toBeUndefined();
  });

  it("BUILTIN_ICONS is the exact value-level mirror of BUILTIN_ICON_IDS", () => {
    expect(Object.keys(BUILTIN_ICONS).sort()).toEqual([...BUILTIN_ICON_IDS].sort());
  });
});
