/**
 * Tier-B icon registry for `@ingcreators/annot-core`.
 *
 * Phase 2 of `docs/plans/svg-icons-and-plugin-icon-spec.md`.
 *
 * Single source of truth for the SVG strings backing every
 * `IconSpec({ kind: "builtin", id })` look-up:
 *
 *   - Material Symbols Outlined glyphs (Apache-2.0, Copyright
 *     Google LLC) extracted from the upstream
 *     `@material-symbols/svg-400` package via
 *     `scripts/extract-material-symbols.mjs`. Per-glyph contents
 *     live in the autogenerated `material-symbols.ts` sibling so
 *     a re-extraction (after an upstream version bump) never
 *     touches the hand-curated parts of this file.
 *   - Hand-rolled groups (`shape.*`, `arrow.*`, `counter.*`)
 *     authored to fill cohesion gaps where Material's stock
 *     glyphs do not visually distinguish (rect vs. rounded vs.
 *     ellipse outlines), where Material's stock glyphs are not a
 *     visual match for the concept (a "single line with
 *     arrowheads on both ends" — Material's `sync_alt` shows two
 *     parallel lines), or where the toolbar wants the variant
 *     glyph to read as the same family at a glance (counter
 *     marker badges, where the numeric "1" reads the same
 *     against three container shapes).
 *
 * The registry is the source of truth for the narrow
 * `BuiltinIconId` literal union exported below. Adding a new id
 * means editing this file — autocomplete + compile-time errors
 * for typos flow to every consumer (host code AND plugin
 * authors who imported via the `/icons` subpath).
 *
 * Tier-B placement: pure data. No DOM access, no Element
 * imports, jsdom-loadable. Sanitisation + DOM injection happen
 * in the renderer (Phase 3).
 */

import { ARROW_ICON_SVG, COUNTER_ICON_SVG, SHAPE_ICON_SVG } from "../toolbar-icons.js";
import { BRAND_GITHUB_SVG, BRAND_GOOGLE_DRIVE_SVG } from "./brand-icons.js";
import { MATERIAL_SYMBOL_GLYPHS } from "./material-symbols.js";

/**
 * Hand-rolled glyphs already shipped from `toolbar-icons.ts`
 * before the migration. Folded in here under dotted ids so the
 * retrieval API is uniform — call sites use
 * `IconSpec({ kind: "builtin", id: "shape.rect" })` rather than
 * importing `SHAPE_ICON_SVG` directly. The original
 * `toolbar-icons.ts` re-exports stay live for back-compat in
 * Phase 2.
 */
const HAND_ROLLED_GLYPHS = {
  // Shape tool variants (rect / rounded / ellipse outlines).
  // Material's `square` / `rectangle` / `crop_square` / `circle`
  // are visually IDENTICAL at 36px button scale — distinguishing
  // by exaggerated corner radius makes the family read.
  "shape.rect": SHAPE_ICON_SVG.rect,
  "shape.rounded": SHAPE_ICON_SVG.rounded,
  "shape.ellipse": SHAPE_ICON_SVG.ellipse,
  // Arrow tool head variants. `sync_alt` would show two parallel
  // lines, not "single line with arrowheads on both ends"; hand-
  // rolling the trio keeps the line length / stroke weight
  // identical so only the head geometry varies.
  "arrow.none": ARROW_ICON_SVG.none,
  "arrow.end": ARROW_ICON_SVG.end,
  "arrow.both": ARROW_ICON_SVG.both,
  // Counter (marker) badge variants. Each glyph is the container
  // shape filled with `currentColor` and a "1" cut out via
  // `fill-rule="evenodd"` so the number reads as panel
  // background, automatically theme-adapting.
  "counter.circle": COUNTER_ICON_SVG.circle,
  "counter.rect": COUNTER_ICON_SVG.rect,
  "counter.rounded": COUNTER_ICON_SVG.rounded,
  // Storage-backend brand marks. Geometry + colours are verbatim
  // from the upstream-published assets so the marks comply with
  // each vendor's brand guidelines (don't modify, don't recolour
  // multi-colour marks). See `brand-icons.ts` for the trademark
  // notice and the rationale for the `currentColor` vs. fixed-
  // palette split.
  "brand.github": BRAND_GITHUB_SVG,
  "brand.google_drive": BRAND_GOOGLE_DRIVE_SVG,
} as const;

/**
 * The full registry. Material Symbols glyphs come first
 * (autogenerated, alphabetic) followed by the hand-rolled
 * groups. Object spread merges them at module-load time;
 * downstream `keyof typeof BUILTIN_ICONS` picks up both groups
 * automatically.
 */
export const BUILTIN_ICONS = {
  ...MATERIAL_SYMBOL_GLYPHS,
  ...HAND_ROLLED_GLYPHS,
} as const;

/**
 * Narrow string-literal union covering every id in the
 * registry. Re-exported from `@ingcreators/annot-core/icons` so
 * plugin authors get autocomplete + compile-time errors on
 * typos.
 *
 * Replaces the broad `string` alias in
 * `@ingcreators/annot-core/icons/types` for callers that want
 * the registry as a value-level dependency. The `IconSpec`
 * descriptor itself still types `id` as the broad alias —
 * runtime equivalence is exact (both are `string`).
 */
export type BuiltinIconId = keyof typeof BUILTIN_ICONS;

/** All registered builtin ids, frozen at module-load time.
 *  Useful for validating plugin-supplied ids and for generating
 *  a Storybook gallery. */
export const BUILTIN_ICON_IDS = Object.keys(BUILTIN_ICONS) as readonly BuiltinIconId[];

/** Resolve a builtin id to its SVG markup, or `undefined` if the
 *  id isn't registered. The renderer (Phase 3) calls this and
 *  treats `undefined` as "no icon" rather than throwing — that
 *  keeps a typo'd plugin id from crashing the host. */
export function resolveBuiltinIcon(id: string): string | undefined {
  return (BUILTIN_ICONS as Record<string, string>)[id];
}
