import { defineConfig } from "@ingcreators/annot-product-docs";

// Living-product-docs config for the docs site itself. Phase 5
// of `docs/plans/annot-work-astro-unification.md` — `annot.work/docs`
// is generated by `annot` from a Playwright tour of `annot.work/app`.
//
// Scope (Open Question #1 resolution): every docs page that
// explains the Annot web app. Phase 5 PR lands the `/docs/app/`
// overview as the proof-of-concept dogfood page; expanding to
// the remaining `/docs/app/*` + screenshot-heavy
// `getting-started` / `recipes` pages is follow-up work that
// doesn't need a plan revision.
//
// The book name is "Annot web app" so the (future) xlsx output
// (out of scope for the docs site itself, but the config is
// shaped consistently with downstream consumers) groups all
// dogfooded pages under one workbook.
export default defineConfig({
  meta: {
    projectName: "Annot",
    description:
      "Annot web app — annotated screenshots in the browser. Dogfood section of annot.work/docs.",
  },
  xlsx: {
    defaultBook: "Annot web app",
    books: {
      "Annot web app": {
        // No `template` configured — the docs site doesn't emit
        // Excel from itself. The block exists so the
        // annot-docs CLI's drift detector groups findings under
        // a sensible book label.
      },
    },
  },
});
