/**
 * Embed-protocol event types — the on-the-wire contract between
 * docs sites (the OSS-side host that renders `<AnnotEditButton>`)
 * and the annot-cloud editor (the iframe / new-tab client). Tier
 * A — pure types + constants, zero runtime deps, browser- +
 * Node-friendly.
 *
 * Phase 5a of `docs/plans/living-spec-authoring-roadmap.md`.
 *
 * Two transports carry these events:
 *
 * - **`inline` mode** (5c): `window.postMessage` between the docs
 *   site's parent window and the annot-cloud iframe. All
 *   `EmbedEvent` variants flow this way.
 *
 * - **`newTab` mode** (5b): URL-callback. Only the post-edit
 *   signals (`EditCommitted` / `EditAbandoned`) round-trip via
 *   the return URL's hash fragment (`#edit-complete=<editId>` /
 *   `#edit-abandoned=1`). `EditorReady` / `EditRequested` /
 *   `ResizeNeeded` are inapplicable in this transport — the new
 *   tab is independent of the parent site's lifecycle.
 *
 * The shared event shape lets the editor-side code in
 * annot-cloud emit one event union regardless of transport;
 * the transport-specific wrappers (5b / 5c) decide which subset
 * of events to forward and how.
 */

/**
 * Wire-format version. Bump when adding a non-additive field
 * or removing an existing one. Additive changes (new event
 * variant, new optional payload field) stay on `1` until a
 * breaking change forces a bump.
 *
 * Both peers exchange the version in the `EditorReady` event;
 * mismatch is a warning, not a hard error — backwards-compatible
 * additions should still work cross-version.
 */
export const EMBED_PROTOCOL_VERSION = 1 as const;
export type EmbedProtocolVersion = typeof EMBED_PROTOCOL_VERSION;

/**
 * Selects how `<AnnotEditButton>` routes the visitor to the
 * annot-cloud editor:
 *
 * - `newTab` (default): `window.open(${cloudUrl}/embed?…)` —
 *   Enterprise-safe, works under strict CSPs / SSO redirects /
 *   third-party cookie bans / on-prem deployments. See
 *   `living-spec-authoring-roadmap.md` OQ-09 for the rationale
 *   behind the default.
 * - `inline` (opt-in): modal `<iframe>` mounted on the docs
 *   site itself. Smooth UX but requires consumer-side CSP
 *   `frame-src` whitelist + third-party cookie support.
 * - `disabled`: button not rendered. For read-only docs / air-
 *   gapped deployments without on-prem annot-cloud.
 */
export type EmbedMode = "newTab" | "inline" | "disabled";

/**
 * Sent from editor → host as soon as the cloud editor is loaded
 * and ready to receive `EditRequested`. Carries the protocol
 * version so the host can warn on mismatch.
 *
 * Transport: `inline` only. `newTab` mode skips this — the new
 * tab is independent of the parent and the host has no postMessage
 * channel to receive it on.
 */
export interface EditorReadyEvent {
  readonly type: "EditorReady";
  readonly protocolVersion: EmbedProtocolVersion;
  /** Per-editor-session identifier; opaque to the host. */
  readonly editorId: string;
}

/**
 * Sent from editor → host after the editor has loaded the
 * target PNG + annotation yaml + started accepting user input.
 * Includes the `editId` the editor will reference in subsequent
 * lifecycle events (`EditCommitted` / `EditAbandoned`).
 *
 * Transport: `inline` only. `newTab` mode carries the same
 * fields in the request URL (see 5b's `encodeEmbedRequestUrl`);
 * the editor doesn't emit a separate `EditRequested` in that
 * transport.
 */
export interface EditRequestedEvent {
  readonly type: "EditRequested";
  /** Generated by the editor — used to correlate with the
   *  matching `EditCommitted` / `EditAbandoned`. */
  readonly editId: string;
  /** Owner/repo slug, e.g. `"ingcreators/annot"`. */
  readonly repo: string;
  /** Path within the repo of the PNG being edited. */
  readonly pngPath: string;
  /** Path within the repo of the linked `.annotations.yaml`. */
  readonly annotationsPath: string;
}

/**
 * Sent from editor → host after the user saves and the cloud
 * editor's commit pipeline succeeds. The host typically dismisses
 * the iframe modal (inline) or surfaces a "site rebuilds in ~1
 * minute" toast on hash-return (newTab).
 *
 * Transport: both. `inline` flows via postMessage; `newTab`
 * flows via the return URL's `#edit-complete=<editId>` hash
 * fragment (5b's `parseEmbedReturnHash`).
 */
export interface EditCommittedEvent {
  readonly type: "EditCommitted";
  /** Matches the `editId` from the corresponding
   *  `EditRequested` (or the URL-encoded `editId` for newTab). */
  readonly editId: string;
  /** Resulting commit SHA — the host can link to it / link to
   *  the PR if `prUrl` is set. */
  readonly commitSha: string;
  /** Branch the commit landed on. Omitted when the cloud
   *  editor committed directly to the default branch and the
   *  branch name is implicit. */
  readonly branch?: string;
  /** If the cloud editor's per-installation policy chose PR
   *  mode (OQ-05), the PR URL to surface to the user. */
  readonly prUrl?: string;
}

/**
 * Sent from editor → host when the user cancels mid-edit OR
 * an unrecoverable save error stops the commit pipeline. The
 * host typically dismisses the modal (inline) without showing
 * a success toast; the docs page state is unchanged.
 *
 * Transport: both. `inline` flows via postMessage; `newTab`
 * uses `#edit-abandoned=1` (5b's hash format).
 */
export interface EditAbandonedEvent {
  readonly type: "EditAbandoned";
  readonly editId: string;
  /** Why the edit was abandoned. Free-form past
   *  `userCancelled` / `saveError` / `authRejected` so the
   *  cloud editor can extend without a protocol bump. */
  readonly reason: "userCancelled" | "saveError" | "authRejected" | (string & {});
}

/**
 * Sent from editor → host when the cloud editor's content height
 * changes (e.g. opening a property panel grows the canvas). The
 * host can use this to grow the iframe so the page-side
 * scrollbar handles the overflow rather than a nested iframe
 * scrollbar.
 *
 * Transport: `inline` only. Irrelevant for `newTab` — the new
 * tab manages its own scroll surface.
 */
export interface ResizeNeededEvent {
  readonly type: "ResizeNeeded";
  /** CSS pixels. Host may clamp to a maximum. */
  readonly width: number;
  /** CSS pixels. Host may clamp to a maximum. */
  readonly height: number;
}

/**
 * Discriminated union of every event that flows over the
 * embed-protocol. Discriminated by `type`.
 *
 * See per-variant JSDoc for transport applicability (some
 * variants are `inline`-only).
 */
export type EmbedEvent =
  | EditorReadyEvent
  | EditRequestedEvent
  | EditCommittedEvent
  | EditAbandonedEvent
  | ResizeNeededEvent;

/**
 * Narrow lookup of every event `type` literal. Useful for
 * exhaustive switches + JSON Schema generation in
 * annot-cloud's `/embed` route. Build error if a new event
 * variant lands without being added here.
 */
export const EMBED_EVENT_TYPES = [
  "EditorReady",
  "EditRequested",
  "EditCommitted",
  "EditAbandoned",
  "ResizeNeeded",
] as const satisfies readonly EmbedEvent["type"][];

export type EmbedEventType = EmbedEvent["type"];

/**
 * Type guard helper. Useful at the postMessage boundary where
 * the runtime payload is untyped.
 */
export function isEmbedEvent(value: unknown): value is EmbedEvent {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as { type?: unknown };
  if (typeof candidate.type !== "string") return false;
  return (EMBED_EVENT_TYPES as readonly string[]).includes(candidate.type);
}
